# -*- coding: utf-8 -*-
"""Tesi04-1-Flair.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XOGA1F4GvYKZpr2DQzyqZOndKiliHOfl

Con questo notebook alleniamo il primo segmenter, quello che utilizzerà le immagini "flair" del dataset.
"""

import os
import tensorflow as tf
import matplotlib.pyplot as plt


SEED = 1234
tf.random.set_seed(SEED)

cwd = os.getcwd() #get current working directory
physical_devices = tf.config.list_physical_devices('GPU') 
#physical_devices = tf.config.list_physical_devices('CPU')

from google.colab import drive
drive.mount('/content/drive')

tf.config.list_physical_devices()



os.environ['DATASET_DRIVE_CUSTOM'] = "/content/drive/MyDrive/Extracted/"
os.environ['DATASET_DRIVE_ADE20K'] = "/content/drive/MyDrive/Dataset/ade20k"
os.environ['DATASET_DRIVE'] = "/content/drive/MyDrive/Dataset/"

os.environ['DATASET_LOCALE'] = "/Massimo/Politecnico/Magistrale/Tesi/Dataset/Extracted/"
os.environ['DATASET_LOCALE_CUSTOM'] = "~/Google\ Drive/Il mio Drive/Dataset/Extracted"
os.environ['DATASET_LOCALE_ADE20K'] = "~/Google\ Drive/Il mio Drive/Dataset/"

os.environ['DATASET_DOCKER_CUSTOM'] = "/workspace/Extracted"
#%cd /content/drive/My Drive/MMSegmentation

#!rm -rf mmsegmentation
#!git clone https://github.com/open-mmlab/mmsegmentation.git
#%cd MMSegmentation
#!pip install -e

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My Drive/Segmenter/custom_dataset_segmenter/
!ls

#%cd mmsegmentation
#!git clone https://github.com/open-mmlab/mmsegmentation.git --branch v0.14.1
#!git checkout 26032167e005f391aad1bf151a7e8f9a98973266

#%cd mmsegmentation

#!git checkout -b 26032167e005f391aad1bf151a7e8f9a98973266

#!conda config --add channels conda-forge
#!conda config --add channels matsci
#!conda config --add channels abinit

# Commented out IPython magic to ensure Python compatibility.
#!conda update conda
# %cd /content/drive/My Drive/Segmenter/custom_dataset_segmenter
#%cd ~/Google\ Drive/Il mio Drive/Segmenter/custom_dataset_segmenter
!ls
#cd ~/Google\ Drive/Il mio Drive/Segmenter/segmenter
!pip install -v -e .
#!pip install .
!pip install --ignore-installed PyYAML

#!conda install --file requirements.txt
#!conda install PyYAML --yes 
# %cd /content/drive/My Drive/Segmenter/custom_dataset_segmenter/mmsegmentation
!pip install -v -e .

os.environ['DATASET'] = os.environ['DATASET_DRIVE_CUSTOM']


#in metrics.py, usa una variabile d'ambiente $WORK: settiamola
os.environ['WORK'] = "/content/drive/MyDrive/WORK/"

!python -m segm.train --log-dir $DATASET_DRIVE_CUSTOM --dataset flair --backbone vit_tiny_patch16_384 --decoder mask_transformer
#!python -m segm.train --log-dir $DATASET_DRIVE_ADE20K --dataset ade20k --backbone vit_tiny_patch16_384 --decoder mask_transformer


#python -m segm.inference --model-path "/content/drive/My Drive/Extracted/checkpoint.pth" -i "/content/drive/My Drive/Immagine" -o segmapsn/



